name: Multi arch build

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'
  workflow_dispatch:

env:
  REGISTRY_IMAGE: oski

jobs:
  build:
    name: Build image
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs_on: ubicloud-standard-8-arm
            arch: arm64
            target: ffmpeg-bin
          - runs_on: ubicloud-standard-8-arm
            arch: arm64
            target: ffmpeg-dev
          - runs_on: ubicloud-standard-8-arm
            arch: arm64
            target: ffmpeg-shared
          - runs_on: ubuntu-latest
            arch: amd64
            target: ffmpeg-bin
          - runs_on: ubuntu-latest
            arch: amd64
            target: ffmpeg-dev
          - runs_on: ubuntu-latest
            arch: amd64
            target: ffmpeg-shared

    runs-on: ${{ matrix.runs_on }}
    steps:
      - uses: actions/checkout@v4
      - name: Docker build
        run: docker build --target ${{ matrix.target }} --tag image:${{ matrix.target }}-${{ matrix.arch }} .
      - name: Docker save
        run: docker image save --output image-${{ matrix.target }}-${{ matrix.arch }}.tar image:${{ matrix.target }}-${{ matrix.arch }}
      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.target }}-${{ matrix.arch }}
          path: image-${{ matrix.target }}-${{ matrix.arch }}.tar
          retention-days: 1

  tag:
    name: Extract tag name
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.tag.outputs.result }}
    steps:
      - name: Extract the tag name
        id: tag
        run: |
          jq -nr '
            ( env.GITHUB_REF
            | split("/")[1:]
            | "result=" + if . == ["heads","master"] then "8.0" else .[1] end
            )
          ' >> "$GITHUB_OUTPUT"

  merge:
    name: Merge and push images
    runs-on: ubuntu-latest
    needs:
      - build
      - tag
    steps:
      - name: Download images
        uses: actions/download-artifact@v4
        with:
          path: /tmp
          pattern: image-*
          merge-multiple: true
      - name: Load Docker images
        run: |
          for image in /tmp/image-*.tar; do
            docker image load --input "$image"
          done
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create manifest lists and push
        run: |
          set -eu
          for target in ffmpeg-bin ffmpeg-dev ffmpeg-shared; do
            suffix=""
            if [ "$target" = "ffmpeg-dev" ]; then suffix="-dev"; fi
            if [ "$target" = "ffmpeg-shared" ]; then suffix="-shared"; fi

            docker tag image:${target}-arm64 ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix}-arm64
            docker tag image:${target}-amd64 ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix}-amd64
            docker push ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix}-arm64
            docker push ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix}-amd64
            docker manifest create \
              ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix} \
              --amend ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix}-arm64 \
              --amend ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix}-amd64
            docker manifest inspect ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix}
            docker manifest push ${{ env.REGISTRY_IMAGE }}:${{ needs.tag.outputs.TAG }}${suffix}
          done
